### ISSUE TITLE
fix navbar

### ISSUE THREAD

**Issue by mnyrop** [cul/ldpd-bunraku#4]
Drop-down navigation bar (pure css) doesn't fly out properly on third level. 
See: Special features > Realia > ... in [demo](https://cul.github.io/ldpd-bunraku/).

Current styling lives in /assets as drop-nav.css

**Comment by er-k** [comment]
https://github.com/cul/ldpd-bunraku/commit/552926f59f3f29a833f5db0f6b63c0d2278d0f73
