### ISSUE TITLE
Hide d3 visualizations if on mobile

### ISSUE THREAD

**Issue by mnyrop** [cul/ldpd-bunraku#5]
The d3 visualizations are individual {% include %} blocks. See [includes/d3/](https://github.com/cul/ldpd-bunraku/tree/master/_includes/d3). It would be great for these to be dynamically hidden based on OS or viewer size...? 

Example: visualization on index: [https://cul.github.io/ldpd-bunraku/](https://cul.github.io/ldpd-bunraku/).

**Comment by er-k** [comment]
i added in a helper class of .hidden-xs but haven't yet implemented it https://github.com/cul/ldpd-bunraku/commit/6b8684a58fc472fc334d33da40b8334c7b69bd61.

after looking things over, i'm wondering if hiding is the best option.  if hidden, the three pages under "Data Visualizations" would be completely useless, right? it might be better to wrap the svg in fixed or max height containing divs and set the [dynamic] height with _viewBox_ and _preserveAspectRatio_.

let's discuss.

**Comment by er-k** [comment]
https://github.com/cul/ldpd-bunraku/commit/051d9c77e016d0e3103003ad9f2ab385d016f452
